const cities = [
  { name: "New York", code: "US", country: "United States" },
  { name: "London", code: "UK", country: "United Kingdom" },
  { name: "Paris", code: "FR", country: "France" },
  { name: "Tokyo", code: "JP", country: "Japan" },
  { name: "Dubai", code: "AE", country: "United Arab Emirates" },
  { name: "Singapore", code: "SG", country: "Singapore" },
  { name: "Sydney", code: "AU", country: "Australia" },
  { name: "Mianwali", code: "PK", country: "Pakistan" },
  { name: "Lahore", code: "PK", country: "Pakistan" },
  { name: "Karachi", code: "PK", country: "Pakistan" },
  { name: "Islamabad", code: "PK", country: "Pakistan" },
  { name: "Faisalabad", code: "PK", country: "Pakistan" },
  { name: "Rawalpindi", code: "PK", country: "Pakistan" },
  { name: "Multan", code: "PK", country: "Pakistan" },
  { name: "Peshawar", code: "PK", country: "Pakistan" },
  { name: "Quetta", code: "PK", country: "Pakistan" },
  { name: "Sialkot", code: "PK", country: "Pakistan" },
  { name: "Gujranwala", code: "PK", country: "Pakistan" },
  { name: "Hyderabad", code: "PK", country: "Pakistan" },
  { name: "Mumbai", code: "IN", country: "India" },
  { name: "Delhi", code: "IN", country: "India" },
  { name: "Toronto", code: "CA", country: "Canada" },
  { name: "Berlin", code: "DE", country: "Germany" },
  { name: "Istanbul", code: "TR", country: "Turkey" },
  { name: "Beijing", code: "CN", country: "China" },
  { name: "Shanghai", code: "CN", country: "China" },
  { name: "Guangzhou", code: "CN", country: "China" },
  { name: "Seoul", code: "KR", country: "South Korea" },
  { name: "Busan", code: "KR", country: "South Korea" },
  { name: "Bangkok", code: "TH", country: "Thailand" },
  { name: "Chiang Mai", code: "TH", country: "Thailand" },
  { name: "Kuala Lumpur", code: "MY", country: "Malaysia" },
  { name: "Jakarta", code: "ID", country: "Indonesia" },
  { name: "Manila", code: "PH", country: "Philippines" },

  { name: "Colombo", code: "LK", country: "Sri Lanka" },
  { name: "Kathmandu", code: "NP", country: "Nepal" },
  { name: "Dhaka", code: "BD", country: "Bangladesh" },
  { name: "Kabul", code: "AF", country: "Afghanistan" },
  { name: "Tehran", code: "IR", country: "Iran" },
  { name: "Baghdad", code: "IQ", country: "Iraq" },
  { name: "Riyadh", code: "SA", country: "Saudi Arabia" },
  { name: "Jeddah", code: "SA", country: "Saudi Arabia" },
  { name: "Doha", code: "QA", country: "Qatar" },
  { name: "Muscat", code: "OM", country: "Oman" },

  { name: "Kuwait City", code: "KW", country: "Kuwait" },
  { name: "Abu Dhabi", code: "AE", country: "United Arab Emirates" },
  { name: "Sharjah", code: "AE", country: "United Arab Emirates" },
  { name: "Cairo", code: "EG", country: "Egypt" },
  { name: "Alexandria", code: "EG", country: "Egypt" },
  { name: "Cape Town", code: "ZA", country: "South Africa" },
  { name: "Johannesburg", code: "ZA", country: "South Africa" },
  { name: "Nairobi", code: "KE", country: "Kenya" },
  { name: "Lagos", code: "NG", country: "Nigeria" },
  { name: "Casablanca", code: "MA", country: "Morocco" },

  { name: "Madrid", code: "ES", country: "Spain" },
  { name: "Barcelona", code: "ES", country: "Spain" },
  { name: "Rome", code: "IT", country: "Italy" },
  { name: "Milan", code: "IT", country: "Italy" },
  { name: "Amsterdam", code: "NL", country: "Netherlands" },
  { name: "Brussels", code: "BE", country: "Belgium" },
  { name: "Vienna", code: "AT", country: "Austria" },
  { name: "Zurich", code: "CH", country: "Switzerland" },
  { name: "Stockholm", code: "SE", country: "Sweden" },
  { name: "Oslo", code: "NO", country: "Norway" },

  { name: "Helsinki", code: "FI", country: "Finland" },
  { name: "Copenhagen", code: "DK", country: "Denmark" },
  { name: "Moscow", code: "RU", country: "Russia" },
  { name: "Athens", code: "GR", country: "Greece" },
  { name: "Lisbon", code: "PT", country: "Portugal" },
  { name: "Mexico City", code: "MX", country: "Mexico" },
  { name: "Los Angeles", code: "US", country: "United States" },
  { name: "Chicago", code: "US", country: "United States" },
  { name: "San Francisco", code: "US", country: "United States" },
  { name: "Rio de Janeiro", code: "BR", country: "Brazil" },
  { name: "Bahawalpur", code: "PK", country: "Pakistan" },
  { name: "Sargodha", code: "PK", country: "Pakistan" },
  { name: "Sheikhupura", code: "PK", country: "Pakistan" },
  { name: "Jhelum", code: "PK", country: "Pakistan" },
  { name: "Gujrat", code: "PK", country: "Pakistan" },
  { name: "Kasur", code: "PK", country: "Pakistan" },
  { name: "Okara", code: "PK", country: "Pakistan" },
  { name: "Sahiwal", code: "PK", country: "Pakistan" },
  { name: "Chiniot", code: "PK", country: "Pakistan" },
  { name: "Toba Tek Singh", code: "PK", country: "Pakistan" },

  { name: "Jhang", code: "PK", country: "Pakistan" },
  { name: "Bhakkar", code: "PK", country: "Pakistan" },
  { name: "Khushab", code: "PK", country: "Pakistan" },
  { name: "Mandi Bahauddin", code: "PK", country: "Pakistan" },
  { name: "Narowal", code: "PK", country: "Pakistan" },
  { name: "Hafizabad", code: "PK", country: "Pakistan" },
  { name: "Attock", code: "PK", country: "Pakistan" },
  { name: "Chakwal", code: "PK", country: "Pakistan" },
  { name: "Murree", code: "PK", country: "Pakistan" },
  { name: "Taxila", code: "PK", country: "Pakistan" },

  { name: "Dera Ghazi Khan", code: "PK", country: "Pakistan" },
  { name: "Muzaffargarh", code: "PK", country: "Pakistan" },
  { name: "Layyah", code: "PK", country: "Pakistan" },
  { name: "Lodhran", code: "PK", country: "Pakistan" },
  { name: "Rahim Yar Khan", code: "PK", country: "Pakistan" },
  { name: "Bahawalnagar", code: "PK", country: "Pakistan" },
  { name: "Pakpattan", code: "PK", country: "Pakistan" },
  { name: "Vehari", code: "PK", country: "Pakistan" },
  { name: "Khanewal", code: "PK", country: "Pakistan" },
  { name: "Mian Channu", code: "PK", country: "Pakistan" },

  { name: "Kot Addu", code: "PK", country: "Pakistan" },
  { name: "Burewala", code: "PK", country: "Pakistan" },
  { name: "Arifwala", code: "PK", country: "Pakistan" },
  { name: "Kamalia", code: "PK", country: "Pakistan" },
  { name: "Kamoke", code: "PK", country: "Pakistan" },
  { name: "Wazirabad", code: "PK", country: "Pakistan" },
  { name: "Sambrial", code: "PK", country: "Pakistan" },
  { name: "Shakargarh", code: "PK", country: "Pakistan" },
  { name: "Muridke", code: "PK", country: "Pakistan" },
  { name: "Nankana Sahib", code: "PK", country: "Pakistan" },

  { name: "Swat", code: "PK", country: "Pakistan" },
  { name: "Mingora", code: "PK", country: "Pakistan" },
  { name: "Abbottabad", code: "PK", country: "Pakistan" },
  { name: "Haripur", code: "PK", country: "Pakistan" },
  { name: "Mansehra", code: "PK", country: "Pakistan" },
  { name: "Dera Ismail Khan", code: "PK", country: "Pakistan" },
  { name: "Bannu", code: "PK", country: "Pakistan" },
  { name: "Kohat", code: "PK", country: "Pakistan" },
  { name: "Gilgit", code: "PK", country: "Pakistan" },
  { name: "Skardu", code: "PK", country: "Pakistan" },
  { name: "Mianwali", code: "PK", country: "Pakistan" },
];

export default cities;
